services:
  bot:
    build: .
    container_name: deepseek_bot
    restart: always
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

  postgres:
    image: postgres:16
    container_name: deepseek_postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT_OUT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: deepseek_redis
    restart: always
    ports:
      - "${REDIS_PORT_OUT}:${REDIS_PORT}"
    env_file:
      - .env
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
